### PR TITLE
System.Void -> void

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Review by danielmarbach — APPROVED** [review]

**Comment by danielmarbach** [comment]
Shouldn't this PR go against the upstream?

**Comment by jnm2** [comment]
@danielmarbach This is a cool idea IMO. When I pull this PR into my branch, it'll appear in https://github.com/ApiApprover/ApiApprover/pull/114.

**Comment by jnm2** [comment]
Gonna go with this one:

image

**Comment by jnm2** [comment]
Oops, thought that was going to be a fast-forward merge. I should learn to read. :D

**Pull request merged**
